name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Tests
        run: cargo test --verbose
      - name: Test1
        run: if [ "$(echo -e "/bin/echo" | cargo run)" = "success" ]; then echo "TEST 1 PASSED"; else echo "TEST 1 FAILED"; exit 105; fi
      - name: Test2
        run: if [ "$(echo -e "/strange_dir/non_ex_file.rs" | cargo run)" = "failure" ]; then echo "TEST 2 PASSED"; else echo "TEST 2 FAILED"; exit 105; fi
      - name: Test3
        run: if [ "$(echo -e "/" | cargo run)" = "failure" ]; then echo "TEST 3 PASSED"; else echo "TEST 3 FAILED"; exit 105; fi
      - name: Test4
        run: if [ "$(echo -e "/dev/opam" | cargo run)" = "failure" ]; then echo "TEST 5 PASSED"; else echo "TEST 5 FAILED"; exit 105; fi
      - name: Test5
        run: if [ "$(echo -e "/bin/systemd" | cargo run)" = "success" ]; then echo "TEST 6 PASSED"; else echo "TEST 6 FAILED"; exit 105; fi
